Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox"

  $num_vms = 3
  (1..$num_vms).each do |id|
    config.vm.define "kube-node#{id}" do |node|
      node.vm.hostname = "kube-node#{id}"
      node.vm.network :private_network, ip: "10.64.3.#{id}",  auto_config: true
      config.vm.network "forwarded_port", guest: 8080, host: 8080 # kube-apiserver
      config.vm.network "forwarded_port", guest: 8086, host: 8086 # kubectl proxy
      config.vm.network "forwarded_port", guest: 443, host: 4443 # harbor
      node.vm.provider :virtualbox do |vb, override|
        vb.name = "kube-node#{id}"
        vb.gui = false
        vb.memory = 2048
        vb.cpus = 1
      end
    end
  end
end
